deactBackend/urls.py
from django.contrib import admin
from django.urls import path
# Use include() to add URLS from the stock and post application and authentication syste
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('api/', include('post.urls')),
]

urlpatterns += [
    path('stock/', include('stock.urls')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/stock/', permanent=True)),
]



#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

post/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ListPost.as_view()),
    path('<int:pk>/', views.DetailPost.as_view()),
]

stock/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('kospis/', views.KospiListView.as_view(), name='kospis'),
    path('kospi/<int:pk>/', views.KospiDetailView.as_view(), name='kospi-detail'),
    path('kosdaks/', views.KosdakListView.as_view(), name='kosdaks'),
    path('kosdak/<int:pk>/', views.KosdakDetailView.as_view(), name='kosdak-detail'),
    path('owners/', views.OwnerListView.as_view(), name='owner'),
    path('owner/<int:pk>/', views.OwnerDetailView.as_view(), name='owner-detail')
]

# Set in Owner of company
urlpatterns += [
    path('mykospis/', views.OwnedKospisByUserListView.as_view(), name='my-kospi'),
    path(r'ownnedkospi/', views.OwnedKospisAllListView.as_view(), name='all-kospi'),
    path('mykosdaks/', views.OwnedKosdaksByUserListView.as_view(), name='my-kosdak'),
    path(r'ownnedkosdak/', views.OwnedKosdaksAllListView.as_view(), name='all-kosdak'),
]

# Add URLConf searching for a stock
urlpatterns += [
    path('Kospi/search/', views.search_kospi_name, name='search_kospi_name'),
    path('Kosdak/search/', views.search_kosdak_name, name='search_kosdak_name'),
]

# Add URLConf to create, update, and delete kospi
urlpatterns += [
    path('owner/create/', views.OwnerCreate.as_view(), name='owner_create'),
    path('owner/<int:pk>/update/', views.OwnerUpdate.as_view(), name='owner_update'),
    path('owner/<int:pk>/delete/', views.OwnerDelete.as_view(), name='owner_delete'),
]
# Add URLConf to create, update, and delete kospi
urlpatterns += [
    path('kospi/create/', views.KospiCreate.as_view(), name='kospi_create'),
    path('kospi/<int:pk>/update/', views.KospiUpdate.as_view(), name='kospi_update'),
    path('kospi/<int:pk>/delete/', views.KospiDelete.as_view(), name='kospi_delete'),
]


# Add URLConf to create, update, and delete kosdak
urlpatterns += [
    path('kosdak/create/', views.KosdakCreate.as_view(), name='kosdak_create'),
    path('kosdak/<int:pk>/update/', views.KosdakUpdate.as_view(), name='kosdak_update'),
    path('kosdak/<int:pk>/delete/', views.KosdakDelete.as_view(), name='kosdak_delete'),
]

stock/models.py
from django.db import models

# Create your models here.

from django.urls import reverse
class Sector(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Kospi(models.Model):
    name = models.CharField(max_length=20)
    code = models.CharField(max_length=8)
    owner = models.ForeignKey('Owner', on_delete=models.SET_NULL, null=True)
    sector = models.ManyToManyField(Sector, null=True)
    feature = models.TextField(null=True)

    def display_sector(self):
        return ', '.join([sector.name for sector in self.sector.all()[:3]])

    display_sector.short_description = 'Sector'

    def get_absolute_url(self):
        return reverse('kospi-detail', args=[str(self.id)])
    def __str__(self):
        return self.name

class Kosdak(models.Model):
    name = models.CharField(max_length=20)
    code = models.CharField(max_length=8)
    owner = models.ForeignKey('Owner', on_delete=models.SET_NULL, null=True)
    sector = models.ManyToManyField(Sector, null=True)
    feature = models.TextField(null=True)

    def display_sector(self):
        return ', '.join([sector.name for sector in self.sector.all()[:3]])

    display_sector.short_description = 'Sector'

    def get_absolute_url(self):
        return reverse('kosdak-detail', args=[str(self.id)])

    def __str__(self):
        return self.name

import uuid
from datetime import date
from django.contrib.auth.models import User

class KospiInstance(models.Model):
    """Model representing a spedific copy of a stock"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,\
        help_text="Unique ID for this particular stock across whole data" ) 
    kospi = models.ForeignKey('Kospi', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    OWN_STAUS = (
        ('d', 'Maintenance'),
        ('h', 'Having'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=OWN_STAUS,
        blank=True,
        default='d',
        help_text='Kospi Ownner ',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (
            ("can_mark_returned", "Set kospi as returned"),
        )

    def __str__(self):
        return '{0} ({1})'.format(self.id, self.kospi.name)


class KosdakInstance(models.Model):
    """Model representing a spedific copy of a stock"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,\
        help_text="Unique ID for this particular stock across whole data" ) 
    kosdak = models.ForeignKey('Kosdak', on_delete=models.SET_NULL, null=True, blank=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    OWN_STATUS = (
        ('d', 'Maintenance'),
        ('h', 'Having'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=OWN_STATUS,
        blank=True,
        default='d',
        help_text='Kosdak user',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (
            ("can_mark_returned", "Set kosdak as returned"),
        )

    def __str__(self):
        return '{0} ({1})'.format(self.id, self.kosdak.name)

class Owner(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('owner-detail', args=[str(self.id)])

    def __str__(self):
        return '{0}, {1}'.format(self.last_name, self.first_name)

stock/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class KospiSearchForm(forms.Form):
    name = forms.CharField(label='Search Word', required=False)
    def clean_name(self):
        cleaned_name = self.cleaned_data['name']

        # Check if a search word is string
        if not self.additional_validate(cleaned_name):
            raise forms.ValidationError(
                self.error_messages['name_incorrect'], code='name_incorrect',
            )
        return cleaned_name


class KosdakSearchForm(forms.Form):
    name = forms.CharField(label='Search Word', required=False)
    def clean_name(self):
        cleaned_name = self.cleaned_data['name']

        # Check if a search word is string
        if not self.additional_validate(cleaned_name):
            raise forms.ValidationError(
                self.error_messages['name_incorrect'], code='name_incorrect',
            )
        return cleaned_name

stock/views.py
from django.shortcuts import render
from rest_framework import generics
from .models import Kospi, Kosdak, KospiInstance, KosdakInstance, Owner

# Create your views here.

def index(request):
    """ View function for home page of site """
    # Generate counts of some of the main objects
    num_kospis = Kospi.objects.all().count()
    num_kospi_instances = KospiInstance.objects.all().count()
    num_kosdaks = Kosdak.objects.all().count()
    num_kosdak_instances = KosdakInstance.objects.all().count()
    # Available copies of stocks
    num_kospi_instance_available = KospiInstance.objects.filter(status__exact='d').count()
    num_kosdak_instance_available = KosdakInstance.objects.filter(status__exact='d').count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    return render(
        request,
        'index.html',
        context={
            'num_kospis': num_kospis, 'num_kospi_instances': num_kospi_instances,
            'num_kospi_instance_available': num_kospi_instance_available,
            'num_kosdaks': num_kosdaks, 'num_kosdak_instances': num_kosdak_instances,
            'num_kosdak_instances_available': num_kosdak_instance_available,
        }
    )
from django.views import generic

class KospiListView(generic.ListView):
    """ Generic class-based view for a list of kospis. """
    model = Kospi
    paginate_by = 10

class KospiDetailView(generic.DetailView):
    """ Generic class-based detail view for a kospis """
    model = Kospi

class KosdakListView(generic.ListView):
    """ Generic class-based view for a list of kospis. """
    model = Kosdak
    paginate_by = 10

class KosdakDetailView(generic.DetailView):
    """ Generic class-based detail view for a kosdaks """
    model = Kosdak

class OwnerListView(generic.ListView):
    """ Generic class-based view for a list of kospis. """
    model = Owner
    paginate_by = 10

class OwnerDetailView(generic.DetailView):
    """ Generic class-based detail view for a kospis """
    model = Owner

from django.contrib.auth.mixins import LoginRequiredMixin

class OwnedKospisByUserListView(LoginRequiredMixin, generic.ListView):
    """ Generic class-based view listing kospis on name to current user. """
    model = KospiInstance
    template_name = 'stock/kospiinstance_list_owned_user.html'
    paginate_by = 10

    def get_queryset(self):
        return KospiInstance.objects.filter(user=self.request.user).filter(status__exact='h').order_by('due_back')


class OwnedKosdaksByUserListView(LoginRequiredMixin, generic.ListView):
    """ Generic class-based view listing kospis on name to current user. """
    model = KosdakInstance
    template_name = 'stock/kosdakinstance_list_owned_user.html'
    paginate_by = 10

    def get_queryset(self):
        return KosdakInstance.objects.filter(user=self.request.user).filter(status__exact='h').order_by('due_back')


# Added as part of challenge!
from django.contrib.auth.mixins import PermissionRequiredMixin


class OwnedKospisAllListView(PermissionRequiredMixin, generic.ListView):
    """Generic class-based view listing all books on loan. Only visible to users with can_mark_returned permission."""
    model = KospiInstance
    permission_required = 'stock.can_mark_returned'
    template_name = 'stock/kospiinstance_list_owned_all.html'
    paginate_by = 10

    def get_queryset(self):
        return KospiInstance.objects.filter(status__exact='o').order_by('due_back')



class OwnedKosdaksAllListView(PermissionRequiredMixin, generic.ListView):
    """Generic class-based view listing all books on loan. Only visible to users with can_mark_returned permission."""
    model = KosdakInstance
    permission_required = 'stock.can_mark_returned'
    template_name = 'stock/kosdakinstance_list_owned_all.html'
    paginate_by = 10

    def get_queryset(self):
        return KosdakInstance.objects.filter(status__exact='o').order_by('due_back')


from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime

# from  .form import SearchForm
from stock.forms import KospiSearchForm, KosdakSearchForm

# Create your views here.
@permission_required('stock.can_mark_returned')
def search_kospi_name1(request):

    #if post, processing data
    if request.method == 'POST':

        #Create a form_instance & binding requsted data
        kospi_form = KosdakSearchForm(request.POST)

        # Chect form validate
        if kospi_form.is_valid():
            # Process data as requsted
            c_name = kospi_form.save(commit=False)
            q_data = Kospi.objects.get(name=c_name)
            print(q_data)
            return HttpResponseRedirect(q_data)
    else:
        context = {
            'form' : KospiSearchForm(),
        }
        return render(request, 'stock/search_kospi_name.html', context)

def search_kospi_name(request):
    qs = Kospi.objects.all()

    q = request.GET.get('q', '')
    if q:
        qs = qs.filter(name__icontains=q)
    context = {
        'object_list' : qs,
        'q' : q,
    }
    return render(request, 'stock/search_kospi_name.html', context)


@permission_required('stock.can_mark_returned')
def search_kosdak_name(request):
    qs = Kosdak.objects.all()

    q = request.GET.get('q', '')
    if q:
        qs = qs.filter(name__icontains=q)
    context = {
        'object_list' : qs,
        'q' : q,
    }
    return render(request, 'stock/search_kosdak_name.html', context)





def search_kosdak_name1(request):
    kosdak_instance = get_object_or_404(KosdakInstance)

    #if post, processing data
    if request.method == 'POST':

        #Create a form_instance & binding requsted data
        kosdak_company_name_form = KosdakSearchForm(request.POST)

        # Chect form validate
        if kosdak_company_name_form.is_valid():
            # Process data as requsted
            kosdak_company_name_data = kosdak_instance.code.filter\
                (name=kosdak_company_name_form.cleaned_company_name['company_name'])
            q_set = Kosdak.objects.get(name=kosdak_company_name_data)
            return HttpResponseRedirect(reverse('all-kosdak'))
    else:
        proposed_search_name = KosdakSearchForm.company_name
        kosdak_company_name_form = KosdakSearchForm(initial={'company_name': proposed_search_name})

    context = {
        'form' : kosdak_company_name_form,
        'kosdak_instance' : kosdak_instance,
    }

    return render(request, 'stock/search_kosdak_name.html', context)

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


# Classes created for the forms challenge
class OwnerCreate(PermissionRequiredMixin, CreateView):
    model = Owner
    fields = '__all__'
    initial = {'date_of_death': '05/01/2018'}
    permission_required = "stock.can_mark_returned"

class OwnerUpdate(PermissionRequiredMixin, UpdateView):
    model = Owner
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    permission_required = 'stock.can_mark_returned'

class OwnerDelete(PermissionRequiredMixin, DeleteView):
    model = Owner
    success_url = reverse_lazy('owners')
    permission_required = 'stock.can_mark_returned'

class KospiCreate(PermissionRequiredMixin, CreateView):
    model = Kospi
    fields = '__all__'
    permission_required = 'stock.can_mark_returned'


class KospiUpdate(PermissionRequiredMixin, UpdateView):
    model = Kospi
    fields = '__all__'
    permission_required = 'stock.can_mark_returned'


class KospiDelete(PermissionRequiredMixin, DeleteView):
    model = Kospi
    success_url = reverse_lazy('kospis')
    permission_required = 'stock.can_mark_returned'

class KosdakCreate(PermissionRequiredMixin, CreateView):
    model = Kosdak
    fields = '__all__'
    permission_required = 'stock.can_mark_returned'


class KosdakUpdate(PermissionRequiredMixin, UpdateView):
    model = Kosdak
    fields = '__all__'
    permission_required = 'stock.can_mark_returned'


class KosdakDelete(PermissionRequiredMixin, DeleteView):
    model = Kosdak
    success_url = reverse_lazy('kosdaks')
    permission_required = 'stock.can_mark_returned'

stock/templates/stock/kosdak_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Kosdak</h1>

<p>Are you sure you want to delete the kosdak: {{ kosdak }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

stock/templates/stock/kosdak_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Kosdak: {{ kosdak }} </h1>
<p>{{kosdak.date_of_birth}} - {% if kosdak.date_of_death %}{{kosdak.date_of_death}}{% endif %}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Kosdaks</h4>

<dl>
{% for kosdak in kosdak.kosdak_set.all %}
  <dt><a href="{% url 'kosdak-detail' kosdak.pk %}">{{kosdak}}</a> ({{kosdak.kosdakinstance_set.all.count}})</dt>
  <dd>{{kosdak.summary}}</dd>
{% endfor %}
</dl>

</div>
{% endblock %}

stock/templates/stock/kosdak_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="get">
    {% csrf_token %}
    <input type="text" name="q" value="{{q}}">
    <input type="submit" value="Search" />
    
</form>
<h3>{{q}}을 입력하였읍니다 </h3>
{% endblock %}

stock/templates/stock/kosdak_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Kosdak List</h1>
    <a href="{% url 'search_kosdak_name'%}">Search Code</a>  

    {% if kosdak_list %}
    <ul>

      {% for kosdak in kosdak_list %}
      <li>
        <a href="{{ kosdak.get_absolute_url }}">{{ kosdak.name }}</a> ({{kosdak.code}})
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no kosdaks in the stock.</p>
    {% endif %}       
{% endblock %}

stock/templates/stock/kosdakinstance_list_owned_all.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Owned Kosdaks</h1>
    <a href="{% url 'search_kosdak_name' %}">Search Code</a>  

    {% if kosdakinstance_list %}
    <ul>

      {% for kosdakinst in kosdakinstance_list %} 
      <li class="{% if kosdakinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'kosdak-detail' kosdakinst.kosdak.pk %}">{{kosdakinst.kosdak.name}}</a>
         ({{ kosdakinst.due_back }}) 
         {% if user.is_staff %}- {{ kosdakinst.user }}
         {% endif %} 
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no kosdaks owned.</p>
    {% endif %}       
{% endblock %}

stock/templates/stock/kosdakinstance_list_owned_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Owned kosdaks</h1>
    <a href="{% url 'search_kosdak_name' %}">Search Code</a>  

    {% if kosdakinstance_list %}
    <ul>

      {% for kosdakinst in kosdakinstance_list %} 
      <li class="{% if kosdakinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'kosdak-detail' kosdakinst.kosdak.pk %}">{{kosdakinst.kosdak.name}}</a> ({{ kosdakinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no kosdaks owned.</p>
    {% endif %}       
{% endblock %}

stock/templates/stock/kospi_comfirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Kospi</h1>

<p>Are you sure you want to delete the kospi: {{ kospi }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

stock/templates/stock/kospi_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Kospi: {{ kospi.pk }} </h1>
<p>{{kospi.date_of_birth}} - {% if kospi.date_of_death %}{{kospi.date_of_death}}{% endif %}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Kospis</h4>

<dl>
{% for kospi in kospi.kospi_set.all %}
  <dt><a href="{% url 'kospi-detail' kospi.pk %}">{{kospi}}</a> ({{kospi.kospiinstance_set.all.count}})</dt>
  <dd>{{kospi.summary}}</dd>
{% endfor %}
</dl>

</div>
{% endblock %}

stock/templates/stock/kospi_from.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="get">
    {% csrf_token %}
    <input type="text" name="q" value="{{q}}">
    <input type="submit" value="Search" />
    
</form>
<h3>{{q}}을 입력하였읍니다 </h3>
{% endblock %}

stock/templates/stock/kospi_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Kospi List</h1>
    <a href="{% url 'search_kospi_name'%}">Search Code</a>  

    {% if kospi_list %}
    <ul>

      {% for kospi in kospi_list %}
      <li>
        <a href="{{ kospi.get_absolute_url }}">{{ kospi.name }}</a> ({{kospi.code}})
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no kospis in the stock.</p>
    {% endif %}       
{% endblock %}

stock/templates/stock/kospiinstance_list_owned_all.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Owned kospis</h1>
    <a href="{% url 'search_kospi_name' %}">Search Code</a>  

    {% if kospiinstance_list %}
    <ul>

      {% for kospiinst in kospiinstance_list %} 
      <li class="{% if kospiinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'kospi-detail' kospiinst.kospi.pk %}">{{kospiinst.kospi.name}}</a> ({{ kospiinst.due_back }}) {% if user.is_staff %}- {{ kospiinst.user }}{% endif %} 
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no kospis owned.</p>
    {% endif %}       
{% endblock %}

stock/templates/stock/kospiinstance_list_owned_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Owned kospis</h1>
    <a href="{% url 'search_kospi_name' %}">Search Code</a>  

    {% if kospiinstance_list %}
    <ul>

      {% for kospiinst in kospiinstance_list %} 
      <li class="{% if kospiinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'kospi-detail' kospiinst.kospi.pk %}">{{kospiinst.kospi.name}}</a> ({{ kospiinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no kospis owned.</p>
    {% endif %}       
{% endblock %}

stock/templates/stock/search_kosdak_name.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="get">
    {% csrf_token %}
    <input type="text" name="q" value="{{q}}">
    <input type="submit" value="Search" />
    
</form>
{% if q %}
<h3>{{q}}을 입력하였읍니다 </h3>
{% for post in object_list %}
<a href="{{ post.get_absolute_url }}">{{ post.code }}</a><br />
{% endfor %}
{% endif %}
{% if object_list %}
{% for post in object_list %}
<a href="{{ post.get_absolute_url }}">{{ post.name }}</a><br />
{% endfor %}
{% elif q %}
Search Word {{ q }} Not Found!
{% endif %}
{% endblock %}

stock/templates/stock/search_kospi_name.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="get">
    {% csrf_token %}
    <input type="text" name="q" value="{{q}}">
    <input type="submit" value="Search" />
    
</form>
{% if q %}
<h3>{{q}}을 입력하였읍니다 </h3>
{% for post in object_list %}
<a href="{{ post.get_absolute_url }}">{{ post.code }}</a><br />
{% endfor %}
{% endif %}
{% if object_list %}
{% for post in object_list %}
<a href="{{ post.get_absolute_url }}">{{ post.name }}</a><br />
{% endfor %}
{% elif q %}
Search Word {{ q }} Not Found!
{% endif %}
{% endblock %}